Server:
  PublicUrl: https://api.dxrating.net
  FrontendUrl: https://dxrating.net
  DefaultEmailDomain: example.com

OpenApi:
  Enabled: false

Email:
  From: noreply@dxrating.net
  FromName: DXRating
  TemplatePath:

Turnstile:
  Enabled: false
  Secret: the-secret

Authentication:
  Jwt:
    Issuer: https://auth.example.com
    Audience: https://app.example.com
    Key: use-a-very-long-string-that-is-at-least-128-bytes-here-or-jwt-will-failed-to-be-created
    AccessTokenExpire: 900
    RefreshTokenExpire: 604800
  OpenIdConnect:
    - Enable: false
      Name: openid-connect
      DisplayName: OpenId Connect
      Authority: https://sso.example.com/
      ClientId: client-id
      ClientSecret: client-secret
      MetadataAddress: https://sso.example.com/.well-known/openid-configuration
      Scopes:
        - openid
        - profile
        - email
      # When MetadataAddress is null, set the following values
      AuthorizationEndpoint: https://sso.example.com/oauth2/authorize
      TokenEndpoint: https://sso.example.com/oauth2/token
      UserInfoEndpoint: https://sso.example.com/oauth2/userinfo
      Claims:
        Email: email
        DisplayName: name
        Identifier: sub
  OAuthProviders:
    - Enable: false
      Type: Google
      Name: google
      DisplayName: Google
      ClientId: client-id
      ClientSecret: client-secret
    - Enable: false
      Type: Discord
      Name: discord
      DisplayName: Discord
      ClientId: client-id
      ClientSecret: client-secret
    - Enable: false
      Type: GitHub
      Name: github
      DisplayName: GitHub
      ClientId: client-id
      ClientSecret: client-secret
  WebAuthn:
    Enable: true
    ServerDomain: https://auth.example.com
    ServerName: AuthDemo
    ServerIcon: https://auth.example.com/images/icon.png
    Origins:
      - https://app.example.com
  Erc4361:
    Enable: true
    FullyQualifiedDomainName: http://localhost:3000
    Uri: http://localhost:3000
